### PR TITLE
API - Build an Avaya Exporter in PowerShell

### PR DESCRIPTION
**Pull request by amonzerol**

### CODE REVIEW

**Review by philippemin — COMMENTED** [review]
So about putting the entire posh-ssh module in the project:
- From what I understand, DLLs aren't exactly things we can just copy-paste onto any windows machine and expect them to work; we could run into compatibility issues.
- We're gonna need to follow posh-ssh's software license 
- I remember we said a benefit of these export scripts is that they are very transparent i.e. clients can see exactly what the scripts are doing. Downloading a module obfuscates some of that. E.g. a mistrusting client could think we changed some of the DLLs if we were malicious. 

@benoitdesnoyers Did you vet this?

**Comment by amonzerol** [comment]
> So about putting the entire posh-ssh module in the project:
> 
>     * From what I understand, DLLs aren't exactly things we can just copy-paste onto any windows machine and expect them to work; we could run into compatibility issues.
> 
>     * We're gonna need to follow posh-ssh's software license
> 
>     * I remember we said a benefit of these export scripts is that they are very transparent i.e. clients can see exactly what the scripts are doing. Downloading a module obfuscates some of that. E.g. a mistrusting client could think we changed some of the DLLs if we were malicious.
> 
> 
> @benoitdesnoyers Did you vet this?

He tested it on Windows and it works, I tested it on Linux and it works

**Comment by amonzerol** [comment]
@philippemin Doing it without a library to abstract the SSH client code away was near impossible. At first I made the script require the module before running it, so a client could run `Install-Module` to get it, but Ben wanted it portable, hence why I downloaded it and commited it to the repo.

**Review by philippemin — APPROVED** [review]
LGTM 👍

**Pull request merged**
